### ISSUE TITLE
Agregar border en las imagenes de perfil

### ISSUE THREAD

**Issue by moudev** [moudev/primera-colaboracion-open-source#23]
**📍 Descripción**
---

**Landing page # 4**

En el archivo `index.css`, en la clase `.section-gallery__card__profile` agregar que la imagen tenga un `border` de `14px`

Ejem:
```CSS
.elemento {
    border: 15px solid var(--variable-CSS);
}
```

[Más información sobre `border`](https://www.w3schools.com/CSSref/pr_border.asp)

**📷 Capturas**
---

- Corrección

![issue-3](https://user-images.githubusercontent.com/13499566/95666712-96619e80-0b19-11eb-824f-bc6b4f9cf3dd.png)
